from distutils.core import setup
from Chessmonk.utils import get_version

setup(name="chessmonk.bin",
	version=get_version(),
	author="Daniel Borgmann",
	author_email="daniel.borgmann@gmail.com",
	url="http://dborg.wordpress.com",
	license="GNU GPL v2 and above",
	packages=["Chessmonk"],
	data_files=[
		("share/chessmonk/images", 
			["data/images/black-bishop.png",
			"data/images/black-king.png",
			"data/images/black-knight.png",
			"data/images/black-pawn.png",
			"data/images/black-queen.png",
			"data/images/black-rook.png",
			"data/images/white-bishop.png",
			"data/images/white-king.png",
			"data/images/white-knight.png",
			"data/images/white-pawn.png",
			"data/images/white-queen.png",
			"data/images/white-rook.png",
			"data/images/white-bishop.png",
			"data/images/light-square.png",
			"data/images/dark-square.png",
			"data/images/border.png",
			"data/eco.positions",
			]),
		("share/pixmaps", ["data/chessmonk.svg"]),
		("share/applications", ["data/chessmonk.desktop"]),
		("share/chessmonk", ["data/chessmonk.glade"]),
		("share/chessmonk", ["data/eco.positions"]),
	],
	scripts=["chessmonk.bin"],)